유저 삭제 API 기능 추가
mash-up-kr/ssam-d-Node pull request #16
Opened 2023-06-23 04:06 UTC by ChanWoongLee

- user 테이블 deletedAt 컬럼추가
- exception log, prisma query log(only local) 추가
- Logger middleware 추가
- prisma soft delete를 위한 middleware 추가 (ex. delete -> update deletedAt 컬럼, select -> where deletedAt = null)
- 유저 삭제 api 테스트 추가

2023-06-23 05:17 UTC, Marades requested changes

2023-06-23 05:23 UTC, Marades commented on src/prisma/prisma.service.ts
> +          params.args['data'] = { deletedAt: new Date() };
- p5: 이 부분 나중에 리팩토링해봐도 잼쓸 듯~

2023-06-24 09:30 UTC, ChanWoongLee commented on src/prisma/prisma.service.ts
> +        params.args['where'] = { deleted: null };
감사링~

2023-06-24 11:55 UTC, Marades approved these changes

2023-06-24 11:56 UTC, merged