Feature/signal
mash-up-kr/ssam-d-Node pull request #19
Opened 2023-06-25 12:13 UTC by hye-on

- signal, trash 도메인 생성
- signal, trash 모듈 생성
- signal,trash repository 생성
- signal 보내기 기능 구현
- trash 저장

2023-06-25 14:36 UTC, ChanWoongLee commented on src/repositories/user-keyword.repository.ts
> +        SELECT uk.user_id AS id , GROUP_CONCAT(k.name) AS keywords, COUNT(k.name) AS count
p3: 아까 말하던건데, 여기 count랑 UserKeyword에 있는 count 안쓰고 있는데 삭제하는게 어떨까~ 
매칭개수는 signal 도메인에서 keyword 보고 보내주면 될듯!

2023-06-25 14:36 UTC, ChanWoongLee commented on src/repositories/user-keyword.repository.ts
> +    console.log(joinedKeywordIds);
p2: 테스트하던 콘솔 삭제해도 될듯~

2023-06-25 14:36 UTC, ChanWoongLee commented on src/modules/signal/signal.service.ts
> +    if (!matchingInfo.length) {
p4: `matchingInfo.length === 0` 하는게 조금 직관적일 수 있겠다

2023-06-26 08:37 UTC, Marades requested changes
고생해쑤~~고민 많이 한 거 같당!!
담엔 테스트 코드도 한 번 짜보자ㅎㅎ

2023-06-26 08:37 UTC, Marades commented on src/modules/signal/signal.controller.ts
> +  async sendSignal(@AuthUser() senderId, @Body() signalReqDto: SignalReqDto) {
authUser로 가져온 유저 id 그냥 userId로 안하고 senderId로 명시한 거 좋았당👍

2023-06-26 08:37 UTC, Marades commented on src/modules/signal/signal.module.ts
> +  ],
p4: 안쓰는 repository가 많은 거 같은데 정리하면 좋을 거 같다

2023-06-26 08:37 UTC, Marades commented on src/modules/signal/signal.module.ts
> +  exports: [SignalService],
SignalService는 왜 내보낸거야?

2023-06-26 08:37 UTC, Marades commented on src/modules/signal/signal.service.ts
> +    if (matchingInfo.length == 0) {
p1: 여기서는 `==` 대신 `===`을 써야해

javascript가 신기한 애라서 동등비교할 때는 조심해야하는데 ==랑 ===의 차이에 대해 한 번 알아보면 좋을 거 같엉~
아래는 javascript trinity라고 유명한 짤~
![trinity-javascript-bw-0](https://github.com/mash-up-kr/ssam-d-Node/assets/26506997/bfdb360d-6bf7-4d94-b042-313103fe75ca)

2023-06-26 08:37 UTC, Marades commented on src/modules/signal/signal.service.ts
> +        } as unknown as Exclude<Signal, 'id'>;
이 부분 머지 되고 나서 어케 고칠지 고민 좀 더 해볼겡

2023-06-26 08:37 UTC, Marades commented on src/repositories/signal.repository.ts
> +      skipDuplicates: true,
p2: signal에서는 `skipDuplicates: true` 옵션이 필요없지 않아?

2023-06-26 08:37 UTC, Marades commented on src/modules/signal/dto/signal-req-dto.ts
> +  keywords: string[];
p3: 시간 될 때 class validator에서 배열 검증하는 부분도 추가해주면 좋을 거 같당~

2023-06-26 12:38 UTC, hye-on commented on src/modules/signal/signal.module.ts
> +  ],
다쓰는것같아!
해당 도메인(signal)에서 다른 도메인(keyword)에 있는 서비스를 호출하는데 
거기에서 쓰는 (user-keyword)레포지토리도 import해야오류안나더라고 이런경우는  다른 도메인 모듈자체를 임포트하는게 좋은건가?

2023-06-29 11:33 UTC, merged