Feature/signal list
mash-up-kr/ssam-d-Node pull request #21
Opened 2023-06-27 09:39 UTC by hye-on

- 시그널 목록 보내기

2023-06-28 07:03 UTC, Marades requested changes
목록 부분만 리뷰 했으

2023-06-29 11:39 UTC, Marades approved these changes

2023-06-29 11:39 UTC, Marades commented on test/mock/data/signal.data.mock.ts
> +export const signalDataObject = [
p4: 변수명은 좀 더 의미가 더 명확하게 드러나게 짓는 게 좋을 거 같당
`mockSignals` 정도?
해당 변수가 mocking한 데이터를 가르키고 있다는 점이 드러나지 않은 거랑 data와 object같이 포괄적인 단어도 가능하다면 지양하는 게 좋다고 생각해

2023-06-29 11:39 UTC, merged

2023-06-29 12:49 UTC, hye-on commented on test/mock/data/signal.data.mock.ts
> +export const signalDataObject = [
오키!

2023-06-29 12:49 UTC, hye-on commented on src/repositories/signal.repository.ts
> +    const signalListEntities = await this.prisma.signal.findMany({ where: { receiverId: receiverId } });
오키 ! 추가로 다른 정렬도 필요할까?